---
general:
  user_id: 5000
  group_id: 5000
  home_dir: /home/dev
vm:
  dir: .devenv
  type: Vagrant
  module:
    Vagrant:
      provider: virtualbox
      server_url:
docker:
  registry:
  -  http://localhost:5000
