---
general:
  home_dir: /Users/jwalstra/Work/Home
vm:
  dir: .devenv
  type: Vagrant
  module:
    Vagrant:
      provider: virtualbox
web:
  port: 5999
  bonjour: 1
helper:
  port: 5998
docker:
  work_dir: /work
  registry:
  - localhost:5000
