---
general:
  home_dir: /Users/jwalstra/Work/Home
vm:
  dir: .devenv
  type: Vagrant
  module:
    Vagrant:
      provider: virtualbox
      server_url:
web:
  port: 6000
  bonjour: 1
docker:
  registry:
  - localhost:5000
