---
containers:
  data:
    type: data
    description: Persistent Data
    image: perl
    required: 1
  pg9_4:
    type: db
    description: PostgreSQL 9.4
    image: pg9_4
    links:
      - data
    services:
      - name: PostgreSQL
        type: postgres
        src_port: 5432
        dst_port: 5432
    required: 1
  mq:
    type: mq
    description: RabbitMQ
    image: rabbitmq
    links:
      - data
    services:
      - name: Rabbit MQ
        type: http
        src_port: 15672
        dst_port: 15672
  work:
    type: work
    description: Work Environment
    image: debian_jessie
    links:
      - data
      - pg9_4
      - mq
    services:
      - name: SSH
        type: ssh
        src_port: 22222
        dst_port: 22
      - name: Catalyst
        type: http
        src_port: 3000
        dst_port: 3000
    envs:
      - name: PLENV_ROOT
        value: /data/plenv
      - name: PERL_VERSION
        value: 5.18.0
    required: 1
  samba:
    type: fs
    description: Samba Access
    image: samba
    tags:
      - samba
    links:
      - data
    services:
      - name: Samba AD
        type: smb
        src_port: 445
        dst_port: 445
      - name: Samba FS
        src_port: 445
        dst_port: 445/udp
      - name: Samba NetBIOS
        type: smb
        src_port: 139
        dst_port: 139
      - name: Samba WINS
        src_port: 137
        dst_port: 137/udp
      - name: Samba DG
        src_port: 138
        dst_port: 138/udp
